---
title: "Dashbords from Evans UW"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard) # always
library(rio)
library(ggplot2)
UOF=import("UOF.XLSX")
table(UOF$Precinct)
names(UOF)

#checking data types
str(UOF,width = 50,strict.width='cut')

#Contingency table of counts
(PrecinctIncident_Type=table(UOF$Precinct,UOF$Incident_Type))

# computing marginal percent (per column) from contingency table
library(magrittr) # for %>%
(PrecintIncident_Type_mgCol=prop.table(PrecinctIncident_Type,
                            margin = 2)%>%round(.,3))



#Making a dataframe
PrecinctIncident_TypeDF=as.data.frame(PrecinctIncident_Type)
names(PrecinctIncident_TypeDF)=c("precint","Incident_Type","counts")

#adding marginal percents:
PrecinctIncident_TypeDF$pctCol=as.data.frame(PrecintIncident_Type_mgCol)[,3]

PrecinctIncident_TypeDF

base1=ggplot(data=PrecinctIncident_TypeDF, 
             aes(x=Incident_Type, y=pctCol,
                 fill=precint)) # fill brings a legend
barDodge= base1 +  geom_bar(stat="identity",
                            position ='dodge') 
barDodge 

barStacked = base1 + geom_bar(stat = "identity",
                              position = 'stack')#default
barStacked 

library(scales)
library(ggplot2)
barStacked= barStacked + geom_text(size = 5,# check below:
                             position = position_stack(vjust = 0.5),# center
                             aes(label=percent(pctCol,accuracy = 0.1)))# percent format

barStacked = barStacked + scale_y_continuous(labels = scales::percent)

barStacked
base2 =ggplot(PrecinctIncident_TypeDF, aes(x = precint, y = pctCol ) )
bars  = base2 + geom_bar( stat = "identity" ) + theme_minimal()
barsFa = bars + facet_grid(~ Incident_Type)  # X


library(rio)
install_formats()
mydata = read.csv("usa_00004.csv")
names(mydata)
str(mydata,width = 70,strict.width='cut')
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="1", "AL")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="2", "AK")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="4", "AZ")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="5", "AR")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="6", "CA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="8", "CO")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="9", "CT")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="10", "DE")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="11", "DC")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="12", "FL")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="13", "GA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="15", "HI")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="16", "ID")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="17", "IL")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="18", "IN")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="19", "IA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="20", "KS")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="21", "KY")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="22", "LA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="23", "ME")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="24", "MD")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="25", "MA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="26", "MI")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="27", "MN")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="28", "MS")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="29", "MO")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="30", "MT")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="31", "NE")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="32", "NV")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="33", "NH")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="34", "NJ")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="35", "NM")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="36", "NY")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="37", "NC")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="38", "ND")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="39", "OH")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="40", "OK")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="41", "OR")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="42", "PA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="44", "RI")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="45", "SC")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="46", "SD")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="47", "TN")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="48", "TX")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="49", "UT")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="50", "VT")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="51", "VA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="53", "WA")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="54", "WV")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="55", "WI")
mydata$STATEFIP <- replace(mydata$STATEFIP, mydata$STATEFIP=="56", "WY")
mydata
mydata <- mydata[!(mydata$HHINCOME==9999999),]
mydata
StateCount_HI=aggregate(data=mydata,
                        HHINCOME~STATEFIP,
                        FUN=median)
StateCount_HI
StateCount_HI=StateCount_HI[order(StateCount_HI$HHINCOME),]
StateCount_HI
head(StateCount_HI,15)
StateCount_HI$Percent=StateCount_HI$HHINCOME/sum(StateCount_HI$HHINCOME)
StateCount_HI$PercentCum=cumsum(StateCount_HI$Percent)
StateCount_HI$HHINCOME.Cum=cumsum(StateCount_HI$HHINCOME)
# see some
head(StateCount_HI,20)


library(rio)
Pollution_index=import("Pollution index.xlsx")
str(Pollution_index)

boxplot(Pollution_index[,c('particlePollution','pop2022')])

clustData=Pollution_index #copy

clustData[-1]=as.data.frame(scale(clustData[-1]))

#change 2
Pollution_index$particlePollution_S=clustData$particlePollution
Pollution_index$pop2022_S=clustData$pop2022

str(clustData[,-1])

set.seed(123)
library(cluster)

distMatrix=cluster::daisy(clustData[,-1])
        
res.pam=cluster::pam(x=distMatrix,
                     k = 3,
                     cluster.only = F)
### change3
Pollution_index$cluster=as.factor(res.pam$clustering)


theVars=c('particlePollution_S','cluster')
aggregate(.~cluster,
          data=Pollution_index[,theVars],
          FUN=median)

#change 4
Pollution_index$cluster=factor(Pollution_index$cluster,
                           levels=c(3,2,1),
                           labels=c("low","mid","best"), 
                           ordered=T)

linkmap=("https://github.com/Rao-Anand/Assignment-3/blob/main/worldMap.geojson")

library(sf)

mapWorld=read_sf("worldMap.geojson")
head(mapWorld)

# change 5
merge(mapWorld,
                   Pollution_index,by.x='NAME',by.y='country')

mapWorldVars=merge(mapWorld,
                   Pollution_index,by.x='NAME',by.y='country')

library(ggplot2)
# plot original map
base=ggplot(data=mapWorld) + geom_sf(fill='grey90',
                                     color=NA) + theme_classic()

colMap= base + geom_sf(data=mapWorldVars,
                       aes(fill=particlePollution),
                       color=NA)
colMap


colMap + scale_fill_gradient(low = 'red',
                             high= 'blue')
clusterMap= base + geom_sf(data=mapWorldVars,
                           aes(fill=cluster),
                           color=NA) # color of border

clusterMap+ scale_fill_brewer(palette ='YlOrRd')

#previously
theLegLabels=c('1_worst',2,'3_best')
theLegTitle="World_Order\n(grey is missing)"

#now
clusterMap+ scale_fill_brewer(palette ='YlOrRd',
                              direction = -1, # color order
                              labels=theLegLabels,
                              name=theLegTitle)

```




[comment]: # (code for plots in this column)

Column {data-width=650}
-----------------------------------------------------------------------



### Level of Force per each precinct in The City of Seattle

```{r}
library(ggplot2)


barsFa + coord_flip()




```


[comment]: # (code for plots in this column)

Column {data-width=350}
-----------------------------------------------------------------------




### Household income per state in U.S

```{r}

# code coming soon
library(ggplot2)
base1=ggplot(data=StateCount_HI,
             aes(x=STATEFIP,HHINCOME.Cum)) + theme_classic()
base2=base1+scale_x_discrete()
bar1=base2  +geom_bar(stat = "identity")
bar2=bar1 + coord_flip() 
bar2


```


[comment]: # (code for plots in this column)

Column {data-width=350}
-----------------------------------------------------------------------




### World Pollution Index

```{r}

# code coming soon

clusterMap

```


